version: "3.9"
services:
  interest_rate_service:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
